# Generated by Django 4.0.4 on 2022-04-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_items', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
            ],
        ),
    ]
