# Generated by Django 4.0.4 on 2022-04-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_registrationdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmrecords',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='farmrecords',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='farmrecords',
            name='period',
            field=models.DateField(max_length=50),
        ),
    ]
